name: Generate API Docs and Save to docs folder
# This Github Action generates API documents using the python `pdoc`
# library, with flags to generate in the "numpy" style.
# The output are HTML documents saved to "docs"

on:
  push:
    branches: ["main"]

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Initialize conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: bci

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda activate bci
          conda info
          pip install .
          pip install pdoc

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.9

      # - name: Install pdoc
      #   run: pip install pdoc

      - name: Generate API documentation
        shell: bash -el {0}
        run: |
          conda activate bci
          pdoc ./bci_essentials -d numpy --logo "https://avatars.githubusercontent.com/u/65678973" -o ./docs

      - name: Remove bci_essentials folder and environment.yml
        run: |
          rm -rf ./bci_essentials
          rm ./environment.yml

      - name: Commit and Push Changes
        run: |
          git config --local user.email "n44412824+anup2ladder@users.noreply.github.com"
          git config --local user.name "anup2ladder"
          git add ./docs
          git add -u ./bci_essentials
          git add -u ./environment.yml
          git commit -m "Auto-generated API docs and removed unnecessary files"
          git push origin main