name: Generate API Docs and Save to docs folder
# This Github Action generates API documents using the python `pdoc`
# library, with flags to generate in the "numpy" style.
# The output are HTML documents saved to "docs"

on:
  push:
    branches: ["main"]

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install bci-essentials pdoc liblsl

      - name: Generate API documentation
        run: pdoc ./bci_essentials -d numpy --logo "https://avatars.githubusercontent.com/u/65678973" -o ./docs

      - name: Commit and push generated documentation
        run: |
          git config --local user.email 'n44412824+anup2ladder@users.noreply.github.com'
          git config --local user.name "anup2ladder"
          git add docs/*
          git commit -m "HTML of API docs automatically generated by pdoc" || echo "No changes to commit"
          git push